### ISSUE TITLE
Wrong edge found

### ISSUE THREAD

**Issue by arrellc** [ivan-usov/photdiag#2]
The script finds the rising edge of the signal, but the falling edge is what we want.  This is just from the setup geometry so it would be nice to have the option to change this

**Comment by arrellc** [comment]
In fact I'm not sure about this!

**Comment by ivan-usov** [comment]
@arrellc , do I understand correctly, that the data can also be left-right reverted?

> In fact I'm not sure about this!

Did you manage to find more info about the setup?

**Comment by arrellc** [comment]
Hi, yes the data could be inverted from the setup of the timetool, so an option to switch the direction would be useful.  In the current data set the direction is the same, I was mistaken.
