### ISSUE TITLE
Add option for sub-pixel accuracy calculation

### ISSUE THREAD

**Issue by arrellc** [ivan-usov/photdiag#6]
The resolution of returning to the cross correlation maximum limits the resolution to a single pixel and the pixelation is evident in a histogram of returned values.  To improve this could a 2nd order polynomial be fitted around the cross correlation maximum and the maximum of the fit be returned?

**Comment by ivan-usov** [comment]
I would be fairly surprised if the sub-pixel resolution improves the quality of the results, but what we can try is to make more granular x-correlation. This will not remove "pixelation" completely, but can reduce the bin size to an arbitrary value.

Fitting to x-correlation peak might just introduce more "magic" parameters, which will overcomplicate the algorithm. We can consider that option too, though
